version: "3.4"
services:
    nginx:
        image: nginx:1.17-alpine
        ports:
            - 8000:8000
            - 8001:8001
            - 8002:8002
        volumes:
            - .:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        # depends_on:
        #     - php

    # php:
    #     build: .docker/php
    #     volumes:
    #         - .:/var/www/html
