version: "3.4"
services:
    # node:
    #     build: ./node
    #     volumes:
    #         - ./node:/usr/src/app
    #         - /usr/src/app/node_modules
    #     depends_on:
    #         - pfa-docker-c2-mysql
    #     entrypoint: dockerize -wait tcp://pfa-docker-c2-mysql:3306 -timeout 300s -wait-retry-interval 5s
    #     command: nodemon index.js

    nginx:
        build: ./nginx
        restart: always
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        # depends_on:
        #     - node
