version: "3.4"
services:
    nginx:
        image: nginx:1.17-alpine
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: ./php
        volumes:
            - .:/var/www/html
        # ports:
        #     - 9000:9000
